# conf/config.yaml
defaults:
  - _self_  # 현재 파일 포함
  - model: finbert_mamba3 # 모델 설정 파일 포함·

experiment:
  name: "default_experiment"
  seed: 34
  checkpoint_dir:  "${hydra:run.dir}/checkpoints"
  metric_dir:  "${hydra:run.dir}/checkpoints"

data:
  # csv_path: "./data/data_phrasebank.csv"
  csv_path: "./data/data_fiqa1.csv"
  batch_size: 8
  num_workers: 2
  test_size: 0.2
  valid_size : 0.1

training:
  epochs: 1
  learning_rate: 1e-6
  # learning_rate: 1e-5
  early_stopping_patience: 2
  weight_decay: 0.01

optuna:
  enabled: True
  n_trials: 1

