_target_: src.models.finbert_mamba3.FinBERT_Mamba3

config:
  embedding: "ProsusAI/finbert"
  num_labels: 3
  dropout_rate: 0.2
  rmsnorm_eps: 1e-6
  mamba_block:
    d_state: 16
    d_conv: 4
    expand: 2
    num_adapter_layers: 25  # Adapter로 쌓을 MambaBlock 계층 수
  adapter_gate_dim: 768  # 보통 d_model과 동일하게 설정
