_target_: src.models.finbert_abligation.FinBERT_SimpleAdapter
config:
  embedding : "ProsusAI/finbert"
  num_labels: 3
  dropout_rate: 0.1
  rmsnorm_eps: 1e-6
  adapter_dim : 32
  num_mlp_layers  : 25