# conf/model/gamba7.yaml
_target_: src.models.gamba7.Gamba7

config:
  embedding: "state-spaces/mamba-130m-hf"
  num_labels: 3
  dropout_rate: 0.1
  rmsnorm_eps: 1e-6
  mamba_block:
    d_state: 16
    d_conv: 4
    expand: 2
    num_cycles: 1  # (6 MambaBlock + 1 AttentionBlock) 사이클 수
  attention_block:
    n_heads: 8
    expand: 4
  num_cycles: 1  # (6 MambaBlock + 1 AttentionBlock) 사이클 수
